name = "ArmaPMC"
prefix = "pmc"
author = "Brett"
mainprefix = "dynulo"
include = ["./include"]
files = ["mod.cpp", "dynulo_pmc_x64.dll", "dynulo_pmc_x64.so", "dynulo_pmc.dll", "dynulo_pmc.so"]

releasebuild = ["@zip {{modname}}", "@zip {{key_name}}"]
