name = "ArmaPMC"
prefix = "pmc"
author = "Brett"
mainprefix = "dynulo"
include = ["./include"]
files = ["mod.cpp", "dynulo_pmc_x64.dll"]

postbuild = ["!extension"]
releasebuild = ["@zip {{modname}}", "@zip {{key_name}}"]

[scripts.extension]
show_output = true
steps_windows = [
    "cd extension && cargo build --release",
    "copy extension\\target\\release\\dynulo_pmc.dll dynulo_pmc_x64.dll"
]
steps_linux = [
    "echo \"Unable to build extension on Linux\""
]

