name: Arma

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_extension:
    strategy:
      matrix:
        arrays: [
          os: { tag: "ubuntu-latest", ext: ".so", target: "i686-unknown-linux-gnu" },
          os: { tag: "ubuntu-latest", ext: ".so", target: "x86_64-unknown-linux-gnu" },
          os: { tag: "windows-latest", ext: ".dll", target: "i686-pc-windows-msvc" },
          os: { tag: "windows-latest", ext: ".dll", target: "x86_64-pc-windows-msvc" },
        ]
    runs-on: ${{ matrix.arrays.os.tag }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install latest
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.arrays.os.target }}
          toolchain: stable
      - name: Cargo Build
        run: cd extension && cargo build --release
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arrays.os.tag }}
          path: extension/target/release/dynulo_pmc${{ matrix.arrays.os.ext }}
          if-no-files-found: error
          retention-days: 30
