name: Release

on:
  release:
    types:
      - published

jobs:
  build_addon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set VERSION env
      run: echo VERSION=${GITHUB_REF:11} >> $GITHUB_ENV
    - name: Build addon with HEMTT
      uses: arma-actions/hemtt
      with:
        command: 'build --release'
    # Upload to GitHub
    - uses: softprops/action-gh-release@v1
      with:
        files: 'releases/pmc_${{ env.VERSION }}.zip'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Upload to Steam Workshop
    - uses: arma-actions/workshop-upload@v1
      with:
        itemId: '2347071898' # Id of item to update
        contentPath: 'releases/${{ env.VERSION }}/@pmc'
        changelog: 'https://github.com/Dynulo/ArmaPMC/releases/tag/v${{ env.VERSION }}'
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
